mod fase10_task_1;
mod fase10_task_2;
mod fase10_task_3;
mod fase10_task_4;
mod fase10_task_5;
mod fase11_task_1;
mod fase11_task_2;
mod fase11_task_3;
mod fase12_task_1;
mod fase12_task_2;
mod fase12_task_3;
mod fase12_task_4;
mod fase12_task_5;
mod fase13_task_1;
mod fase14_task_1;
use rust_learning_lab::fase14_task_2;
use rust_learning_lab::fase14_task_3;
use rust_learning_lab::mini_project_14;
mod fase2_task_1;
mod fase2_task_2;
mod fase2_task_3;
mod fase2_task_4;
mod fase2_task_5;
mod fase3_task_1;
mod fase3_task_2;
mod fase3_task_3;
mod fase5_task_1;
mod fase5_task_2;
mod fase5_task_3;
mod fase5_task_4;
mod fase6_task_1;
mod fase6_task_2;
mod fase6_task_3;
mod fase6_task_4;
mod fase7_task_1;
mod fase7_task_2;
mod fase7_task_3;
mod fase7_task_4;
mod fase7_task_5;
mod fase8_task_1;
mod fase9_task_1;
mod fase9_task_2;
mod mini_project_1;
mod mini_project_10;
mod mini_project_11;
mod mini_project_12;
mod mini_project_13;
mod mini_project_2;
mod mini_project_3;
mod mini_project_4;
mod mini_project_6;
mod mini_project_7;
mod mini_project_9;
mod task_1;
mod task_2;
mod task_3;
mod task_4;
mod task_5;

fn main() {
    task_1::run();
    println!();
    task_2::run();
    println!();
    task_3::run();
    println!();
    task_4::run();
    println!();
    task_5::run();
    println!();
    mini_project_1::run();
    println!();
    fase2_task_1::run();
    println!();
    fase2_task_2::run();
    println!();
    fase2_task_3::run();
    println!();
    fase2_task_4::run();
    println!();
    fase2_task_5::run();
    println!();
    mini_project_2::run();
    println!();
    fase3_task_1::run();
    println!();
    fase3_task_2::run();
    println!();
    fase3_task_3::run();
    println!();
    mini_project_3::run();
    println!();
    mini_project_4::run();
    println!();
    fase5_task_1::run();
    println!();
    fase5_task_2::run();
    println!();
    fase5_task_3::run();
    println!();
    fase5_task_4::run();
    println!();
    fase6_task_1::run();
    println!();
    fase6_task_2::run();
    println!();
    fase6_task_3::run();
    println!();
    fase6_task_4::run();
    println!();
    mini_project_6::run();
    println!();
    fase7_task_1::run();
    println!();
    fase7_task_2::run();
    println!();
    fase7_task_3::run();
    println!();
    fase7_task_4::run();
    println!();
    fase7_task_5::run();
    println!();
    mini_project_7::run();
    println!();
    fase8_task_1::run();
    println!();
    fase9_task_1::run();
    println!();
    fase9_task_2::run();
    println!();
    mini_project_9::run();
    println!();
    fase10_task_1::run();
    println!();
    fase10_task_2::run();
    println!();
    fase10_task_3::run();
    println!();
    fase10_task_4::run();
    println!();
    fase10_task_5::run();
    println!();
    mini_project_10::run();
    println!();
    fase11_task_1::run();
    println!();
    fase11_task_2::run();
    println!();
    fase11_task_3::run();
    println!();
    mini_project_11::run();
    println!();
    fase12_task_1::run();
    println!();
    fase12_task_2::run();
    println!();
    fase12_task_3::run();
    println!();
    fase12_task_4::run();
    println!();
    fase12_task_5::run();
    println!();
    mini_project_12::run();
    println!();
    fase13_task_1::run();
    println!();
    mini_project_13::run();
    println!();
    fase14_task_1::run();
    println!();
    fase14_task_2::run();
    println!();
    fase14_task_3::run();
    println!();
    mini_project_14::run();
}
